---

- name: Setup Java prerequisties for {{ ansible_os_family }}
  include_tasks: setup-Redhat.yaml
  when: ansible_os_family == 'RedHat' or
        ansible_os_family == 'Suse'

- name: Setup Java prerequisties for {{ ansible_os_family }}
  include_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Ensure Java is installed
  package: 
    name: "{{ java_packages }}"
    state: "present"