---

  - name: Install Java GPG key
    rpm_key:
      key: "{{ java_yum_gpg_key }}"
      state: present

  - name: Install Java repository
    get_url:
      url: "{{ java_yum_repo_url }}"
      dest: "{{ java_yum_repo_name }}"
      owner: root
      group: root
      mode: 0644