---

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config 
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh
  when: ssh_disable_root_access == true

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config 
    regexp: "^PasswordAuthentication" 
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh
  when: ssh_disable_password_authentication == true