---

- name: Load OS Specific vars for {{ ansible_os_family }}
  include_vars: "{{ ansible_os_family }}.yaml"

- name: Install minimal packages for {{ ansible_os_family }} distribution
  include_tasks: setup-{{ ansible_os_family }}.yaml