---

- name: Include defaults vars
  include_vars: "main.yaml"

- name: Define additonal repos
  set_fact:
    additional_repos: "{{ __additional_repos }}"
  when: additional_repos is not defined

- name: Install additional packages for {{ ansible_os_family }}
  include_tasks: setup-{{ ansible_os_family }}.yaml
  when: additional_packages is defined and
        additional_packages | length > 0