---

# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition)
docker_edition: 'ce'
docker_package: 'docker-{{ docker_edition }}'
docker_package_state: present

# Service Options
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Docker compose options
docker_compose_install: true
docker_compose_version: "latest"
docker_compose_release_url: "https://api.github.com/repos/docker/compose/releases/latest"
docker_compose_url: "https://github.com/docker/compose/releases/download"
docker_compose_path: "/usr/local/bin/docker-compose"

# TODO: Debian specific
docker_apt_repo_url: ""

# Redhat specific
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
docker_yum_gpg_key: "https://download.docker.com/linux/centos/gpg"

# A list of users who will be added to docker group
docker_users: ["vagrant"]