  - hosts: all
    become: yes
    vars_files:
      - vars/main.yaml
    roles:
      - update-os
      - server-hardening
      - install-dev-packages
      - geerlingguy.docker
      - geerlingguy.java
      - geerlingguy.firewall
      - geerlingguy.jenkins
      - install-additional-packages